config/routes.rb
Rails.application.routes.draw do
	get 'shop_settings/report'
	get 'shop_settings/display'
  resources :shop_settings

  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'shop_settings#display'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::SessionStorage
  has_one :shop_setting
end

app/models/shop_setting.rb
class ShopSetting < ApplicationRecord
	belongs_to :shop
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ShopifyApp::AuthenticatedController
  def index
    @products = ShopifyAPI::Product.find(:all, params: { limit: 10 })
    @webhooks = ShopifyAPI::Webhook.find(:all)
  end
end

app/controllers/shop_settings_controller.rb
class ShopSettingsController < ShopifyApp::AuthenticatedController
  before_action :set_shop_setting, only: [:show, :edit, :update, :destroy]

  # GET /shop_settings
  # GET /shop_settings.json
  def index
    @shop_settings = ShopSetting.all
  end

  def display
    @current_shop = ShopifyAPI::Shop.current
    @shop = Shop.find_by(:"shopify_domain" == @current_shop)
    if @shop.shop_setting.class == NilClass
      @shop_setting = ShopSetting.new
      @shop_setting.admin_email = ShopifyAPI::Shop.current.email
      @shop_setting.inventory_limit = 5
      @shop_setting.email_notification_frequency = 2
      @shop_setting.email_subscription = true
      @shop_setting.inventory_auto_restock = 5
      @shop_setting.shop_id =@shop.id
      @shop_setting.save
      @demo = ShopifyAPI::AccessScope
      p "hello"
     else
       p "hi"
     end
  end

  def report
    @current_shop = ShopifyAPI::Shop.current
    @shop = Shop.find_by(:"shopify_domain" == @current_shop)
    @products = ShopifyAPI::Product.find(:all, params: { limit: 250 })
    respond_to do |format|
      format.html
      format.json
      format.pdf do 
        render pdf: "report"
      end
    end
  end

  # GET /shop_settings/1
  # GET /shop_settings/1.json
  def show
    @current_shop = ShopifyAPI::Shop.current
    @shop = Shop.find_by(:"shopify_domain" == @current_shop)
  end

  # GET /shop_settings/new
  def new
    @shop_setting = ShopSetting.new
  end

  # GET /shop_settings/1/edit
  def edit
    @current_shop = ShopifyAPI::Shop.current
    @shop = Shop.find_by(:"shopify_domain" == @current_shop)
  end

  # POST /shop_settings
  # POST /shop_settings.json
  def create
    @shop_setting = ShopSetting.new(shop_setting_params)

    respond_to do |format|
      if @shop_setting.save
        format.html { redirect_to @shop_setting, notice: 'Shop setting was successfully created.' }
        format.json { render :show, status: :created, location: @shop_setting }
      else
        format.html { render :new }
        format.json { render json: @shop_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shop_settings/1
  # PATCH/PUT /shop_settings/1.json
  def update
    respond_to do |format|
      if @shop_setting.update(shop_setting_params)
        format.html { redirect_to @shop_setting, notice: 'Shop setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop_setting }
      else
        format.html { render :edit }
        format.json { render json: @shop_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shop_settings/1
  # DELETE /shop_settings/1.json
  def destroy
    @shop_setting.destroy
    respond_to do |format|
      format.html { redirect_to shop_settings_url, notice: 'Shop setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop_setting
      @shop_setting = ShopSetting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_setting_params
      params.require(:shop_setting).permit(:admin_email, :inventory_limit, :email_notification_frequency, :email_subscription, :inventory_auto_restock, :shop_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shop_settings_helper.rb
module ShopSettingsHelper
end

app/views/home/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({ title: "Home" });
    });
  </script>
<% end %>
<h2>Products</h2>

<ul>
  <% @products.each do |product| %>
    <li><%= link_to product.title, "https://#{@shop_session.url}/admin/products/#{product.id}", target: "_top" %></li>
  <% end %>
</ul>

<hr>

<h2>Webhooks</h2>

<% if @webhooks.present? %>
  <ul>
    <% @webhooks.each do |webhook| %>
      <li><%= webhook.topic %> : <%= webhook.address %></li>
    <% end %>
  </ul>
<% else %>
  <p>This app has not created any webhooks for this Shop. Add webhooks to your ShopifyApp initializer if you need webhooks</p>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
<script type="text/javascript">
  var eventName = typeof(Turbolinks) !== 'undefined' ? 'turbolinks:load' : 'DOMContentLoaded';

  if (!document.documentElement.hasAttribute("data-turbolinks-preview")) {
    document.addEventListener(eventName, function flash() {
      <% if flash[:notice] %>
        ShopifyApp.flashNotice("<%= j flash[:notice].html_safe %>");
      <% end %>

      <% if flash[:error] %>
        ShopifyApp.flashError("<%= j flash[:error].html_safe %>");
      <% end %>
                             
      document.removeEventListener(eventName, flash)
    });
  }
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LowStockInventoryNotificationApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>

    <script type="text/javascript">
      ShopifyApp.init({
        apiKey: "<%= ShopifyApp.configuration.api_key %>",
        shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
        debug: <%= Rails.env.development? ? 'true' : 'false' %>,
        forceRedirect: true
      });
    </script>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>

app/views/shop_settings/_form.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>



<div class="container">
  <div class="row">
    <div class="col-sm-9">  
    </div>
    <div class="col-sm-3">
      <%= link_to "Setting", shop_setting_path(@shop.shop_setting.id) %> |
      <%= link_to "Report", shop_settings_report_path %> |
      <%= link_to "Plan", shop_settings_display_path %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-9">
      <div class="card">
        <div class="card-header">
          Customized your settings
        </div>
        <div class="card-body">
            <h5 class="card-title"></h5>
            <%= form_with(model: shop_setting, local: true) do |form| %>
              <% if shop_setting.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(shop_setting.errors.count, "error") %> prohibited this shop_setting from being saved:</h2>

                  <ul>
                  <% shop_setting.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="field">
                <%= form.label :admin_email %>
                <%= form.text_field :admin_email %>
              </div>

              <div class="field">
                <%= form.label :inventory_limit %>
                <%= form.range_field :inventory_limit, min:5, max:100, step:1 %>
              </div>

              <div class="field">
                <%= form.label :email_notification_frequency %>
                <%= form.range_field :email_notification_frequency, min:1, max:24, step:2 %>
              </div>

              <div class="field">
                <%= form.label :email_subscription %>
                <%= form.check_box :email_subscription %>
              </div>

              <div class="field">
                <%= form.label :inventory_auto_restock %>
                <%= form.range_field :inventory_auto_restock %>
              </div>

              <div class="actions">
                <%= form.submit "update", :class => "btn btn-primary" %>
                <%= link_to 'Show', @shop_setting, class:"btn btn-primary" %>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shop_settings/edit.html.erb
<%= render 'form', shop_setting: @shop_setting %>

app/views/shop_settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shop Settings</h1>

<table>
  <thead>
    <tr>
      <th>Admin email</th>
      <th>Inventory limit</th>
      <th>Email notification frequency</th>
      <th>Email subscription</th>
      <th>Inventory auto restock</th>
      <th>Shop</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shop_settings.each do |shop_setting| %>
      <tr>
        <td><%= shop_setting.admin_email %></td>
        <td><%= shop_setting.inventory_limit %></td>
        <td><%= shop_setting.email_notification_frequency %></td>
        <td><%= shop_setting.email_subscription %></td>
        <td><%= shop_setting.inventory_auto_restock %></td>
        <td><%= shop_setting.shop_id %></td>
        <td><%= link_to 'Show', shop_setting %></td>
        <td><%= link_to 'Edit', edit_shop_setting_path(shop_setting) %></td>
        <td><%= link_to 'Destroy', shop_setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop Setting', new_shop_setting_path %>

app/views/shop_settings/new.html.erb
<h1>New Shop Setting</h1>

<%= render 'form', shop_setting: @shop_setting %>

<%= link_to 'Back', shop_settings_path %>

app/views/shop_settings/report.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>


<div class="container">
	<div class="row">
		<div class="col-sm-9">	
    	</div>
    	<div class="col-sm-3">
      		<%= link_to "Setting", shop_setting_path(@shop.shop_setting.id) %> |
      		<%= link_to "Report", shop_settings_report_path %> |
      		<%= link_to "Plan", shop_settings_display_path %> |
      		<%= link_to "Download_PDF", shop_settings_report_path(:format => :pdf)   %>
    	</div>
 	</div>
 	<div class="row">
 		<div class="col-sm-9">
			<div class="card">
				<div class="card-header">
					All Low Inventory Product
				</div>
				<div class="card-body">
			    	<h5 class="card-title"></h5>
			    	<table class="table table-hover">
					  <thead>
					    <tr>
					      <th scope="col">#</th>
					      <th scope="col">Product Name</th>
					      <th scope="col">Inventory Quantity</th>
					    </tr>
					  </thead>
					  <tbody>
					  <% @count = 0%>
					  <% @products.each do |product|%>
					  <% if product.variants[0].attributes[:"inventory_quantity"] < 5 %>
					    <tr>
					      <th scope="row"> <%= @count %></th>
					      <td><%= link_to "#{product.title}", "https://#{@shop_session.url}/admin/products/#{product.id}", target: "_top" %></td>
					      <td><%= product.variants[0].attributes[:"inventory_quantity"] %></td>
					      <% @count = @count + 1 %>
					      <% end %>
					    </tr>
					    <% end %>
					  </tbody>
					</table>
			    	<a href="#" class="btn btn-primary">Go somewhere</a>

			  </div>
			</div>
		</div>
	</div>
</div>

app/views/shop_settings/report.pdf.erb
<div class="container">
 	<div class="row">
 		<div class="col-sm-9">
			<div class="card">
				<div class="card-header">
					All Low Inventory Product
				</div>
				<div class="card-body">
			    	<h5 class="card-title"></h5>
			    	<table class="table table-hover">
					  <thead>
					    <tr>
					      <th scope="col">#</th>
					      <th scope="col">Product Name</th>
					      <th scope="col">Inventory Quantity</th>
					    </tr>
					  </thead>
					  <tbody>
					  <% @count = 0%>
					  <% @products.each do |product|%>
					  <% if product.variants[0].attributes[:"inventory_quantity"] < 5 %>
					    <tr>
					      <th scope="row"> <%= @count %></th>
					      <td><%= link_to "#{product.title}", "https://#{@shop_session.url}/admin/products/#{product.id}", target: "_top" %></td>
					      <td><%= product.variants[0].attributes[:"inventory_quantity"] %></td>
					      <% @count = @count + 1 %>
					      <% end %>
					    </tr>
					    <% end %>
					  </tbody>
					</table>
			    	<a href="#" class="btn btn-primary">Go somewhere</a>
			    	
			  </div>
			</div>
		</div>
	</div>
</div>

app/views/shop_settings/show.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>



<div class="container">
  <div class="row">
    <div class="col-sm-9">
          
      </div>
      <div class="col-sm-3">
          <%= link_to "Setting", shop_setting_path(@shop.shop_setting.id) %> |
          <%= link_to "Report", shop_settings_report_path %> |
          <%= link_to "Plan", shop_settings_display_path %>
      </div>
  </div>
  <div class="card">
    <div class="card-header">
      Admin Settings
    </div>
    <div class="card-body">
    <h5 class="card-title"></h5>
      <div class="row">
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Settings <p id="notice"><%= notice %></p></h5>
              <p class="card-text">
                <strong>Admin email:</strong>
                <%= @shop_setting.admin_email %></br>
                <strong>Inventory limit:</strong>
                <%= @shop_setting.inventory_limit %></br>
                <strong>Email notification frequency:</strong>
                <%= @shop_setting.email_notification_frequency %></br>
                <strong>Email subscription:</strong>
                <%= @shop_setting.email_subscription %></br>
                <strong>Inventory auto restock:</strong>
                <%= @shop_setting.inventory_auto_restock %></br>
              </p>
              <%= link_to 'Edit', edit_shop_setting_path(@shop_setting), :class => "btn btn-primary" %>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Your Current Plan</h5>
              <p class="card-text">
               <strong> Global Inventory Warning Level</strong></br>
                <strong> Email Notification Frequency</strong></br>
                <strong> Export Low Stock Products PDF </strong></br>
                <strong> Change Inventory from Email </strong></br>
                <strong> Add Multiple Email Addresses for Alerts </strong></br>
              </p>
              <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>